#
#  Copyright (c) 2023, 2024 T-Systems International GmbH
#  Copyright (c) 2023 ZF Friedrichshafen AG
#  Copyright (c) 2023 Mercedes-Benz Tech Innovation GmbH
#  Copyright (c) 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
#  Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#

install:
  postgresql: true

image:
#  repository: ghcr.io/catenax-ng/tx-knowledge-agents-edc/agentplane-hashicorp
#  tag: 1.12.19-SNAPSHOT

controlplane:
  endpoints:
    management:
      authKey: "bla"

token:
  signer:
    # alias under which the private key is stored in the vault (JWK or PEM format)
    privatekey_alias: "key"
  verifier:
    # alias under which the public key is stored in the vault, that belongs to the private key ("privatekey_alias", JWK or PEM format)
    publickey_alias: "cert"

iatp:
  sts:
    oauth:
      token_url: "http://keycloak/oauth/token"
    client:
      id: "dummy"
      secret_alias: "dummy"
    dim:
      url: "http://sts.server"

vault:
  azure:
    name: "AZURE_NAME"
    tenant: "AZURE_TENANT"
    client: "AZURE_CLIENT"
    secret: "AZURE_SECRET"
  hashicorp:
    url: "https://vault.demo"
    token: "VAULT_TOKEN"
    paths:
      secret: "/v1/secrets"
  secretNames:
    transferProxyTokenSignerPrivateKey: "key"
    transferProxyTokenSignerPublicKey: "cert"
    transferProxyTokenEncryptionAesKey: "symmetric-key"
participant:
  id: "BPNL0000000DUMMY"
